#!/bin/bash

rm -rf ./Sefaria-Project
git clone --depth=1 --branch=master https://github.com/Sefaria/Sefaria-Project.git Sefaria-Project
rm -rf !$/.git

rm -rf dump_small.tar.gz
rm -rf dump
wget https://storage.googleapis.com/sefaria-mongo-backup/dump_small.tar.gz
tar xzvf dump_small.tar.gz
rm -rf dump_small.tar.gz

docker-compose build
