#!/bin/bash

# abort on any failure
set -e

# (
# cd web \
# && rm -rf Sefaria-Project \
# && git clone --depth=1 --branch=master https://github.com/orenfromberg/sefaria-reddit-torahbot.git Sefaria-Project \
# && rm -rf !$/.git
# )

(
cd mongo \
&& rm -f dump_small.tar.gz \
&& rm -rf dump \
&& wget https://storage.googleapis.com/sefaria-mongo-backup/dump_small.tar.gz
)

docker-compose build --pull

# rm mongo/dump_small.tar.gz

