 FROM python:2.7
 
 ENV PYTHONUNBUFFERED 1
 ENV PYTHONPATH /www
 ENV DJANGO_SETTINGS_MODULE sefaria.settings
 
 RUN apt-get -y update \ 
   && apt-get -y upgrade \
   && apt-get install -y sqlite3 libsqlite3-dev gettext 

 RUN mkdir /db \
  && /usr/bin/sqlite3 /db/db.sqlite

 RUN mkdir /www \
  && mkdir /www/log
 
 # This assumes that code is already in ./Sefaria-Project 
 COPY ./Sefaria-Project /www/
 COPY ./local_settings.py /www/sefaria/
 
 WORKDIR /www
 
 RUN pip install -r requirements.txt \
  && cp -R ./locale/en/LC_MESSAGES/ /usr/local/lib/python2.7/site-packages/django/conf/locale/en \
  && python manage.py syncdb --noinput
 
 ENV NVM_DIR /usr/local/nvm

 # Install nvm with node and npm
 RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install node \  
  && npm install \
  && cp ./node/local_settings_example.json ./node/local_settings.json \
  && npm run build
